# -*- coding: utf-8 -*-
"""salary predction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OPFmILv4QRvmwQOp7k47y9ykCxjjMfAi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sd=pd.read_csv('/content/drive/MyDrive/sd.csv')
print(sd)

sd.head(10)

sd.dtypes

sd.shape

sd.info

sd.isnull().sum()

sd.describe()

plt.figure(figsize=(12,6))
sns.pairplot(sd,x_vars=['YearsExperience'],y_vars=['Salary'],size=7,kind='scatter')
plt.xlabel('years')
plt.ylabel('salary')
plt.title('salary predction')
plt.show()

X=sd['YearsExperience']
X.head()

Y=sd['Salary']
Y.head()

# Import Segregating data from scikit learn
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test= train_test_split(X,Y, train_size=0.7, random_state=100)

X_train = X_train[:,np.newaxis]
X_test = X_test[:,np.newaxis]

from sklearn.linear_model import LinearRegression

lr= LinearRegression()
lr.fit(X_train, Y_train)

Y_predct=lr.predict(X_test)
Y_predct

c = [i for i in range (1,len(Y_test)+1,1)]
plt.plot(c,Y_test,color='r',linestyle='-')
plt.plot(c,Y_predct,color='b',linestyle='-')
plt.xlabel('Salary')
plt.ylabel('index')
plt.title('Prediction')
plt.show()

# plotting the error
c = [i for i in range(1,len(Y_test)+1,1)]
plt.plot(c,Y_test-Y_predct,color='green',linestyle='-')
plt.xlabel('index')
plt.ylabel('Error')
plt.title('Error Value')
plt.show()

from sklearn.metrics import r2_score, mean_squared_error

mse=mean_squared_error(Y_test,Y_predct)

print(mse)

rsq=r2_score(Y_test, Y_predct)
print(rsq)

# Just plot actual and predicted values for more insights
plt.figure(figsize=(12,6))
plt.scatter(Y_test,Y_predct,color='r',linestyle='-')
plt.show()

# Intecept and coeff of the line
print('Intercept of the model:',lr.intercept_)
print('Coefficient of the line:',lr.coef_)